"""
Django settings for analpat project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import json
import boto3

from environs import Env
env = Env() 
env.read_env()
from botocore.exceptions import ClientError

# -----------------------------
# AWS Secrets Manager
# -----------------------------

def get_secrets():
    secret_name = "Django_IP_Tools"
    region_name = "eu-north-1"
    session = boto3.session.Session()
    client = session.client(
        service_name='secretsmanager',
        region_name=region_name,
        # ✅ Read from environment variables, not hardcoded
        aws_access_key_id=os.environ.get("AWS_ACCESS_KEY_ID"),
        aws_secret_access_key=os.environ.get("AWS_SECRET_ACCESS_KEY")
    )
    try:
        get_secret_value_response = client.get_secret_value(SecretId=secret_name)
        return json.loads(get_secret_value_response['SecretString'])
    except Exception as e:
        print(f"FAILED TO FETCH SECRETS: {e}")
        return os.environ



# AWS Configuration
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', 'my-patent-analytics-media')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'eu-north-1')
AWS_DEFAULT_REGION = os.environ.get('AWS_DEFAULT_REGION', 'eu-north-1')
AWS_SECRETS = get_secrets()

# S3 Configuration
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}

# Use S3 for file storage
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'



# Now set your variables using .get() to avoid KeyErrors
SECRET_KEY = AWS_SECRETS.get("DJANGO_SECRET_KEY", "fallback-key-for-now")
# ... other variables ...
POSTGRES_HOST = "db" # Hardcode this to the SERVICE name from your docker-compose.yml

# Use .get() to prevent crashes if a key is missing
SECRET_KEY = AWS_SECRETS.get("DJANGO_SECRET_KEY")
OPENAI_API_KEY = AWS_SECRETS.get("OPENAI_API_KEY")

# Database settings
POSTGRES_USER = AWS_SECRETS.get("POSTGRES_USER")
POSTGRES_PASSWORD = AWS_SECRETS.get("POSTGRES_PASSWORD")
POSTGRES_DB = AWS_SECRETS.get("POSTGRES_DB")

# IMPORTANT: Ensure this matches the SERVICE name in docker-compose.yml
# If your service is named 'db', use 'db'. 
# If it's named 'postgres_db', use 'postgres_db'.
POSTGRES_HOST = AWS_SECRETS.get("POSTGRES_HOST", "db") 
POSTGRES_PORT = AWS_SECRETS.get("POSTGRES_PORT", "5432")

print(f"--- DEBUG: Database Host is set to: {POSTGRES_HOST} ---")


CLOUDINARY_STORAGE = {
    'CLOUD_NAME': AWS_SECRETS['CLOUDINARY_CLOUD_NAME'],
    'API_KEY': AWS_SECRETS['CLOUDINARY_API_KEY'],
    'API_SECRET': AWS_SECRETS['CLOUDINARY_API_SECRET'],
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent





# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = AWS_SECRETS.get("DJANGO_DEBUG", "False") == "True"




'''
# ALLOWED_HOSTS = ["patent-analysis-e57ee02125bf.herokuapp.com", "localhost", "127.0.0.1"]
ALLOWED_HOSTS = ['wwww.ip-xpert.com', 'ip-xpert.com', '*']

CSRF_TRUSTED_ORIGINS =['https://wwww.ip-xpert.com', 'https://ip-xpert.com']
'''

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "*"]
CSRF_TRUSTED_ORIGINS = ["http://127.0.0.1", "http://localhost"]
SECURE_SSL_REDIRECT = False  # disable HTTPS redirect for local dev
SECURE_HSTS_SECONDS = 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    # Third-party
    "crispy_forms",
    "crispy_bootstrap5",
    "allauth", 
    "allauth.account",
    "debug_toolbar",
    'cloudinary',
    'cloudinary_storage',
    # Local
    "accounts.apps.AccountsConfig",  #New custom user
    "pages.apps.PagesConfig",
]
AUTH_USER_MODEL = "accounts.CustomUser"  #New custom user


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    'analpat.session_cache_middleware.SessionCacheControlMiddleware', 

]

ROOT_URLCONF = "analpat.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "analpat.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
"""
DATABASES = {
    "default": env.dj_db_url(
        "DATABASE_URL", default="postgres://postgres@db/postgres")

}
"""
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": AWS_SECRETS["POSTGRES_DB"],
        "USER": AWS_SECRETS["POSTGRES_USER"],
        "PASSWORD": AWS_SECRETS["POSTGRES_PASSWORD"],
        "HOST": AWS_SECRETS["POSTGRES_HOST"],
        "PORT": AWS_SECRETS.get("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# django-crispy-forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5" 

# django-allauth config

LOGIN_REDIRECT_URL = "home"
ACCOUNT_LOGOUT_REDIRECT = "home"
SITE_ID = 2

AUTHENTICATION_BACKENDS = (
"django.contrib.auth.backends.ModelBackend",
"allauth.account.auth_backends.AuthenticationBackend",
)
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = "email" 
ACCOUNT_EMAIL_REQUIRED = True 
ACCOUNT_UNIQUE_EMAIL = True 
DEFAULT_FROM_EMAIL = "juan_d@wp.pl"

MEDIA_URL = "/media/" 
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# django-debug-toolbar
import socket
hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
INTERNAL_IPS = [ip[:-1] + "1" for ip in ips]
'''
SECURE_SSL_REDIRECT = env.bool("DJANGO_SECURE_SSL_REDIRECT", default=True)
SECURE_HSTS_SECONDS = env.int("DJANGO_SECURE_HSTS_SECONDS", default=2592000) # 30 days
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",default=True)
SECURE_HSTS_PRELOAD = env.bool("DJANGO_SECURE_HSTS_PRELOAD", default=True)
SESSION_COOKIE_SECURE = env.bool("DJANGO_SESSION_COOKIE_SECURE", default=True)
CSRF_COOKIE_SECURE = env.bool("DJANGO_CSRF_COOKIE_SECURE", default=True)
'''
SECURE_SSL_REDIRECT = False 
SECURE_HSTS_SECONDS = 0  # This stops the browser from forcing HTTPS
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Store sessions in Redis (optional but recommended for multi-process setups)
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

#Redis cache
if os.getenv("USE_REDIS_CACHE", "0") == "1":
    # Redis cache for production
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": "redis://redis:6379/1",  # "redis" is the Docker service name
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
            "KEY_PREFIX": "transcend"  # optional namespace
        }
    }
else:
    # Local memory cache for development
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }

# --- Celery ---
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://redis:6379/0")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default="redis://redis:6379/1")


